services:
  app:
    image: richardsmnjtk/sre-test-app:latest
    container_name: php-app

  nginx:
    image: richardsmnjtk/sre-test-nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - app
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf

    command: postgres -c config_file=/etc/postgresql/postgresql.conf
volumes:
  postgres_data:
