CREATE DATABASE sre;

CREATE USER fullaccess WITH PASSWORD 'fullaccess123';
CREATE USER readonly WITH PASSWORD 'readonly123';

GRANT ALL PRIVILEGES ON DATABASE sre TO fullaccess;
GRANT CONNECT ON DATABASE sre TO readonly;

\connect sre

GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

GRANT ALL PRIVILEGES ON SCHEMA public TO fullaccess;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO fullaccess;

ALTER DEFAULT PRIVILEGES FOR USER fullaccess IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
